import {wca} from './static/wcarecords.js';
const {world_records, continental_records, national_records} = wca;

let puzzles = {
    '222so': '222',
    '333': '333',
    '444wca': '444',
    '555wca': '555',
    '666wca': '666',
    '777wca': '777',
    '333oh': '333oh',
    '333ni': '333bf',
    '333ft': '333ft',
    'clkwca': 'clock',
    'mgmp': 'minx',
    'pyrso': 'pyram',
    'skbso': 'skewb',
    'sqrs': 'sq1',
    '444bld': '444bf',
    '555bld': '555bf'
};

let countriesDictionary = {
    'Afghanistan': 'Afghanistan',
    'Albania': 'Albania',
    'Algeria': 'Algeria',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Antigua and Barbuda': 'Antigua and Barbuda',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaijan',
    'Bahamas': 'Bahamas',
    'Bahrain': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belarus': 'Belarus',
    'Belgium': 'Belgium',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bhutan': 'Bhutan',
    'Bolivia': 'Bolivia',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Botswana': 'Botswana',
    'Brazil': 'Brazil',
    'Brunei': 'Brunei',
    'Bulgaria': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cabo Verde': 'Cabo Verde',
    'Cambodia': 'Cambodia',
    'Cameroon': 'Cameroon',
    'Canada': 'Canada',
    'Central African Republic': 'Central African Republic',
    'Chad': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Colombia': 'Colombia',
    'Comoros': 'Comoros',
    'Congo': 'Congo',
    'Costa Rica': 'Costa Rica',
    'Cote d_Ivoire': 'Côte d\'Ivoire',
    'Croatia': 'Croatia',
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    'Czech Republic': 'Czech Republic',
    'Democratic People_s Republic of Korea': 'Democratic People\'s Republic of Korea',
    'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
    'Denmark': 'Denmark',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominica',
    'Dominican Republic': 'Dominican Republic',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt',
    'El Salvador': 'El Salvador',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Eritrea': 'Eritrea',
    'Estonia': 'Estonia',
    'Eswatini': 'Eswatini',
    'Ethiopia': 'Ethiopia',
    'Federated States of Micronesia': 'Federated States of Micronesia',
    'Fiji': 'Fiji',
    'Finland': 'Finland',
    'France': 'France',
    'Gabon': 'Gabon',
    'Gambia': 'Gambia',
    'Georgia': 'Georgia',
    'Germany': 'Germany',
    'Ghana': 'Ghana',
    'Greece': 'Greece',
    'Grenada': 'Grenada',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinea',
    'Guinea Bissau': 'Guinea Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hong Kong': 'Hong Kong',
    'Hungary': 'Hungary',
    'Iceland': 'Iceland',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iran': 'Iran',
    'Iraq': 'Iraq',
    'Ireland': 'Ireland',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Jamaica': 'Jamaica',
    'Japan': 'Japan',
    'Jordan': 'Jordan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kiribati': 'Kiribati',
    'Kosovo': 'Kosovo',
    'Kuwait': 'Kuwait',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Laos': 'Laos',
    'Latvia': 'Latvia',
    'Lebanon': 'Lebanon',
    'Lesotho': 'Lesotho',
    'Liberia': 'Liberia',
    'Libya': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Macau': 'Macau',
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaysia',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Marshall Islands': 'Marshall Islands',
    'Mauritania': 'Mauritania',
    'Mauritius': 'Mauritius',
    'Mexico': 'Mexico',
    'Moldova': 'Moldova',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Morocco': 'Morocco',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibia',
    'Nauru': 'Nauru',
    'Nepal': 'Nepal',
    'Netherlands': 'Netherlands',
    'New Zealand': 'New Zealand',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'North Macedonia': 'North Macedonia',
    'Norway': 'Norway',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Palau': 'Palau',
    'Palestine': 'Palestine',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papua New Guinea',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Poland': 'Poland',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'Korea': 'Republic of Korea',
    'Romania': 'Romania',
    'Russia': 'Russia',
    'Rwanda': 'Rwanda',
    'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
    'Saint Lucia': 'Saint Lucia',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Samoa': 'Samoa',
    'San Marino': 'San Marino',
    'Sao Tome and Principe': 'São Tomé and Príncipe',
    'Saudi Arabia': 'Saudi Arabia',
    'Senegal': 'Senegal',
    'Serbia': 'Serbia',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Singapore': 'Singapore',
    'Slovakia': 'Slovakia',
    'Slovenia': 'Slovenia',
    'Solomon Islands': 'Solomon Islands',
    'Somalia': 'Somalia',
    'South Africa': 'South Africa',
    'South Sudan': 'South Sudan',
    'Spain': 'Spain',
    'Sri Lanka': 'Sri Lanka',
    'Sudan': 'Sudan',
    'Suriname': 'Suriname',
    'Sweden': 'Sweden',
    'Switzerland': 'Switzerland',
    'Syria': 'Syria',
    'Taiwan': 'Taiwan',
    'Tajikistan': 'Tajikistan',
    'Tanzania': 'Tanzania',
    'Thailand': 'Thailand',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Tunisia': 'Tunisia',
    'Turkey': 'Turkey',
    'Turkmenistan': 'Turkmenistan',
    'Tuvalu': 'Tuvalu',
    'Uganda': 'Uganda',
    'Ukraine': 'Ukraine',
    'United Arab Emirates': 'United Arab Emirates',
    'United Kingdom': 'United Kingdom',
    'USA': 'United States',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Uzbekistan',
    'Vanuatu': 'Vanuatu',
    'Vatican City': 'Vatican City',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Vietnam',
    'Yemen': 'Yemen',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe'
};

let continentIds = {
    'Afghanistan': '_Asia',
    'Albania': '_Europe',
    'Algeria': '_Africa',
    'Andorra': '_Europe',
    'Angola': '_Africa',
    'Antigua and Barbuda': '_North America',
    'Argentina': '_South America',
    'Armenia': '_Europe',
    'Australia': '_Oceania',
    'Austria': '_Europe',
    'Azerbaijan': '_Europe',
    'Bahamas': '_North America',
    'Bahrain': '_Asia',
    'Bangladesh': '_Asia',
    'Barbados': '_North America',
    'Belarus': '_Europe',
    'Belgium': '_Europe',
    'Belize': '_North America',
    'Benin': '_Africa',
    'Bhutan': '_Asia',
    'Bolivia': '_South America',
    'Bosnia and Herzegovina': '_Europe',
    'Botswana': '_Africa',
    'Brazil': '_South America',
    'Brunei': '_Asia',
    'Bulgaria': '_Europe',
    'Burkina Faso': '_Africa',
    'Burundi': '_Africa',
    'Cabo Verde': '_Africa',
    'Cambodia': '_Asia',
    'Cameroon': '_Africa',
    'Canada': '_North America',
    'Central African Republic': '_Africa',
    'Chad': '_Africa',
    'Chile': '_South America',
    'China': '_Asia',
    'Colombia': '_South America',
    'Comoros': '_Africa',
    'Congo': '_Africa',
    'Costa Rica': '_North America',
    'Cote d_Ivoire': '_Africa',
    'Croatia': '_Europe',
    'Cuba': '_North America',
    'Cyprus': '_Europe',
    'Czech Republic': '_Europe',
    'Democratic People_s Republic of Korea': '_Asia',
    'Democratic Republic of the Congo': '_Africa',
    'Denmark': '_Europe',
    'Djibouti': '_Africa',
    'Dominica': '_North America',
    'Dominican Republic': '_North America',
    'Ecuador': '_South America',
    'Egypt': '_Africa',
    'El Salvador': '_North America',
    'Equatorial Guinea': '_Africa',
    'Eritrea': '_Africa',
    'Estonia': '_Europe',
    'Eswatini': '_Africa',
    'Ethiopia': '_Africa',
    'Federated States of Micronesia': '_Oceania',
    'Fiji': '_Oceania',
    'Finland': '_Europe',
    'France': '_Europe',
    'Gabon': '_Africa',
    'Gambia': '_Africa',
    'Georgia': '_Europe',
    'Germany': '_Europe',
    'Ghana': '_Africa',
    'Greece': '_Europe',
    'Grenada': '_North America',
    'Guatemala': '_North America',
    'Guinea': '_Africa',
    'Guinea Bissau': '_Africa',
    'Guyana': '_South America',
    'Haiti': '_North America',
    'Honduras': '_North America',
    'Hong Kong': '_Asia',
    'Hungary': '_Europe',
    'Iceland': '_Europe',
    'India': '_Asia',
    'Indonesia': '_Asia',
    'Iran': '_Asia',
    'Iraq': '_Asia',
    'Ireland': '_Europe',
    'Israel': '_Europe',
    'Italy': '_Europe',
    'Jamaica': '_North America',
    'Japan': '_Asia',
    'Jordan': '_Asia',
    'Kazakhstan': '_Asia',
    'Kenya': '_Africa',
    'Kiribati': '_Oceania',
    'Kosovo': '_Europe',
    'Kuwait': '_Asia',
    'Kyrgyzstan': '_Asia',
    'Laos': '_Asia',
    'Latvia': '_Europe',
    'Lebanon': '_Asia',
    'Lesotho': '_Africa',
    'Liberia': '_Africa',
    'Libya': '_Africa',
    'Liechtenstein': '_Europe',
    'Lithuania': '_Europe',
    'Luxembourg': '_Europe',
    'Macau': '_Asia',
    'Madagascar': '_Africa',
    'Malawi': '_Africa',
    'Malaysia': '_Asia',
    'Maldives': '_Asia',
    'Mali': '_Africa',
    'Malta': '_Europe',
    'Marshall Islands': '_Oceania',
    'Mauritania': '_Africa',
    'Mauritius': '_Africa',
    'Mexico': '_North America',
    'Moldova': '_Europe',
    'Monaco': '_Europe',
    'Mongolia': '_Asia',
    'Montenegro': '_Europe',
    'Morocco': '_Africa',
    'Mozambique': '_Africa',
    'Myanmar': '_Asia',
    'Namibia': '_Africa',
    'Nauru': '_Oceania',
    'Nepal': '_Asia',
    'Netherlands': '_Europe',
    'New Zealand': '_Oceania',
    'Nicaragua': '_North America',
    'Niger': '_Africa',
    'Nigeria': '_Africa',
    'North Macedonia': '_Europe',
    'Norway': '_Europe',
    'Oman': '_Asia',
    'Pakistan': '_Asia',
    'Palau': '_Oceania',
    'Palestine': '_Asia',
    'Panama': '_North America',
    'Papua New Guinea': '_Oceania',
    'Paraguay': '_South America',
    'Peru': '_South America',
    'Philippines': '_Asia',
    'Poland': '_Europe',
    'Portugal': '_Europe',
    'Qatar': '_Asia',
    'Korea': '_Asia',
    'Romania': '_Europe',
    'Russia': '_Europe',
    'Rwanda': '_Africa',
    'Saint Kitts and Nevis': '_North America',
    'Saint Lucia': '_North America',
    'Saint Vincent and the Grenadines': '_North America',
    'Samoa': '_Oceania',
    'San Marino': '_Europe',
    'Sao Tome and Principe': '_Africa',
    'Saudi Arabia': '_Asia',
    'Senegal': '_Africa',
    'Serbia': '_Europe',
    'Seychelles': '_Africa',
    'Sierra Leone': '_Africa',
    'Singapore': '_Asia',
    'Slovakia': '_Europe',
    'Slovenia': '_Europe',
    'Solomon Islands': '_Oceania',
    'Somalia': '_Africa',
    'South Africa': '_Africa',
    'South Sudan': '_Africa',
    'Spain': '_Europe',
    'Sri Lanka': '_Asia',
    'Sudan': '_Africa',
    'Suriname': '_South America',
    'Sweden': '_Europe',
    'Switzerland': '_Europe',
    'Syria': '_Asia',
    'Taiwan': '_Asia',
    'Tajikistan': '_Asia',
    'Tanzania': '_Africa',
    'Thailand': '_Asia',
    'Timor-Leste': '_Asia',
    'Togo': '_Africa',
    'Tonga': '_Oceania',
    'Trinidad and Tobago': '_North America',
    'Tunisia': '_Africa',
    'Turkey': '_Europe',
    'Turkmenistan': '_Asia',
    'Tuvalu': '_Oceania',
    'Uganda': '_Africa',
    'Ukraine': '_Europe',
    'United Arab Emirates': '_Asia',
    'United Kingdom': '_Europe',
    'USA': '_North America',
    'Uruguay': '_South America',
    'Uzbekistan': '_Asia',
    'Vanuatu': '_Oceania',
    'Vatican City': '_Europe',
    'Venezuela': '_South America',
    'Vietnam': '_Asia',
    'Yemen': '_Asia',
    'Zambia': '_Africa',
    'Zimbabwe': '_Africa'
};

function setCountriesLocale(locale) {
    Object.keys(locale).map((country) => {
        countriesDictionary[country] = locale[country];
    });
}

export let parser = {
    init: (plusLang = {}) => {
        setCountriesLocale(plusLang.PLUS_WCA_COUNTRIES);
    },
    listCountries: () => {
        let countries = [];
        Object.keys(countriesDictionary).map((country) => {
            countries.push({
              label: countriesDictionary[country],
              value: country,
            });
        });
        countries.sort((a, b) => {
            return a.label.localeCompare(b.label);
        });
        return countries;
    },
    getRecords: (puzzle) => {
        let country = kernel.getProp('plusWcaRecordCountry');
        if (country in continentIds && puzzle in puzzles) {
            puzzle = puzzles[puzzle];
            return {
                wr: world_records[puzzle] || {},
                cr: continental_records[continentIds[country]]?.[puzzle] || {},
                nr: national_records[country]?.[puzzle] || {}
            }
        }
    },
}